endpointID: 111111111111_222222222222_3333333333333
Agent Version: IBMBigFixInventory-Scanner-CS-X.Y.Z
Catalog Version: XXXXXXX.Y
Operating System: OSName OSDescription OSArchitecture
DNS Name: HostName
Computer Name: HostName
IP Address:  IPAddress1
 IPAddress2
 IPAddress3
